### PR TITLE
General updates in preparation for upcoming CKB2021 hard fork.

### PR DESCRIPTION
**Pull request by jordanmack**
This is a general rollout PR that introduces a number of changes in preparation for the upcoming CKB2021 hard fork.

- Resolved issues: #10, #12, #13, #14, #19, #27
- Add support for Omni Lock as the default. (PW-Lock is still supported.)
- Update all dependencies to the newest versions possible.
- Fix all tests and added additional tests.
- Fix numerous undocumented issues.
- Add various new minor features.
- Add new fully functional examples that can be run from the command line.
- Add new documentation for the CKB2021 changes.

### CODE REVIEW

**Comment by jordanmack** [comment]
@Kuzirashi In the latest commit, you can now specify the lock type as an option. I will also add documentation around this.

```typescript
import PWCore, {Address, AddressType, IndexerCollector, LockType, Platform, RawProvider, SUDT} from '@lay2/pw-core';

// Public RPC servers provided by Lay2.
const CKB_NODE_RPC_URL = 'https://testnet.ckb.dev/rpc';
const CKB_INDEXER_RPC_URL = 'https://testnet.ckb.dev/indexer';

// The following private key corresponds with CKB native address ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqf8y2wrqq8y3up36e8mqg3tj8wkeyqs8uccxpsdt.
const PRIVATE_KEY = '0xd9066ff9f753a1898709b568119055660a77d9aae4d7a4ad677b8fb3d2a571e5';

(async function main()
{
    const provider = new RawProvider(PRIVATE_KEY, Platform.eth);
    const collector = new IndexerCollector(CKB_INDEXER_RPC_URL);
    const _pwcore = await new PWCore(CKB_NODE_RPC_URL).init(provider, collector);

    const ckbAddress1 = provider.address;
    const ckbAddress2 = new Address(provider.address.toCKBAddress(undefined, LockType.pw), AddressType.ckb);
    const sudt = new SUDT(provider.address.toLockScript(LockType.pw).toHash());

    const options = {lockType: LockType.pw};

    const sudtBalance1 = await collector.getSUDTBalance(sudt, ckbAddress1);
    const sudtBalance2 = await collector.getSUDTBalance(sudt, ckbAddress1, options);
    const sudtBalance3 = await collector.getSUDTBalance(sudt, ckbAddress2);
    const sudtBalance4 = await collector.getSUDTBalance(sudt, ckbAddress2, options);

    console.log(sudtBalance1.toString());
    console.log(sudtBalance2.toString());
    console.log(sudtBalance3.toString());
    console.log(sudtBalance4.toString());
})();
```

```txt
0
0.00000003
0.00000003
0.00000003
```

**Comment by Kuzirashi** [comment]
@jordanmack 

The problem is sendSUDT method is calling IndexerCollector.getSUDTBalance under the hood, and sendSUDT method doesn't support customization of collector options.

**Comment by jordanmack** [comment]
@Kuzirashi Thanks, I will review and merge the PR shortly. 

I noticed the default maximum is 1000 CKB for addresses. That's over $13 USD right now. That seems to be kind of high for the default range. Does it actually need to be that high?

```ts
protected maximumOutputCellCapacity = new Amount('1000', AmountUnit.ckb);
```

**Comment by Kuzirashi** [comment]
@jordanmack 

This is supposed to be failsafe mechanism if something goes wrong with the automatic calculation of fee or someone attacks user via frontend code. 1000 CKB is arbitrarily chosen number. I think it can be lower. I don't think I've ever hit a scenario where I needed more than 500. I would put new maximumOutputCellCapacity in range between 500 and 1000 CKB.

**Comment by jordanmack** [comment]
I'm thinking now that perhaps it would be beneficial to allow the `LockType` specification on the `Address` itself in the constructor for all address types except `AddressType.ckb`.

```ts
Address(address: string, addressType: AddressType, lockType: LockType)
```

It could be set once at the beginning to ensure it doesn't change later. It could still be overridden in `toCKBAddress()` at any point.

**Comment by jordanmack** [comment]
@Kuzirashi Looking closer at what you encountered with `SimpleSUDTBuilder`, I see that the other builders will need to be modified. However, the issue is more complicated since there are now multiple levels where the lock can be overridden.

Specifying the lock type in the address seems like the most simple way to get the desired effect, and it is also more simple for the user.

If you need to force PW-Lock, you would create your address like this and then you don't need any params to the builders.

```ts
new Address('0x7aaff596c5e5e788effa0be946014b794cdd8d51', AddressType.eth, undefined, LockType.pw);
```

What do you think on this?

**Comment by Kuzirashi** [comment]
> @Kuzirashi Looking closer at what you encountered with `SimpleSUDTBuilder`, I see that the other builders will need to be modified. However, the issue is more complicated since there are now multiple levels where the lock can be overridden.
> 
> Specifying the lock type in the address seems like the most simple way to get the desired effect, and it is also more simple for the user.
> 
> If you need to force PW-Lock, you would create your address like this and then you don't need any params to the builders.
> 
> ```ts
> new Address('0x7aaff596c5e5e788effa0be946014b794cdd8d51', AddressType.eth, undefined, LockType.pw);
> ```
> 
> What do you think on this?

Looks quite elegant.

**Pull request merged**
